name: 908BrantleyDr
favicon: null
layout_spectrum: 0.44337588269263506
typography_spectrum: 0.8820091360248625
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000f00'
    - '#9e948b'
    - '#0099e4'
    - '#e2d8cf'
    - '#10edff'
  brandStrength: 0.5
  lightness: 0.4375
  saturation: 0.6875
  rhythmicContrast: 0.34000400360673666
purpose: []
