name: 908BrantleyDr
favicon: null
layout_spectrum: 0.44337588269263506
typography_spectrum: 0.8820091360248625
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.9787673754617572
  lightness: 0.12311269016936421
  saturation: 0.8237502889242023
  rhythmicContrast: 0.34000400360673666
purpose: []
